#!/usr/bin/env python3

import datetime

import requests
from subprocess import check_output

MAILGUN_SMTP_LOGIN = ""
MAILGUN_SMTP_PASSWORD = ""

# Get patch
patch = check_output(["git", "format-patch", "--stdout", "-1", "HEAD"])
print(patch)


def send_simple_message(subject, msg):
    return requests.post(
        "https://api.mailgun.net/v3/<update-yours>/messages",
        auth=("api", ""),
        data={
            "from": "GradCafe Updater <>",
            "to": [""],
            "subject": subject,
            "text": msg,
        },
    )


send_simple_message(f"GradCafe Update {datetime.datetime.now().isoformat()}", patch)
